#setup packages for Data Analytics
install.packages("tm")
install.packages("shiny")
install.packages("smacof")
install.packages("readxl")
install.packages("xtable")
install.packages("DT")
install.packages("yaml")
install.packages("rJava")
install.packages("ReporteRs")
install.packages("wordcloud")
install.packages("wordcloud2")
install.packages("ggplot2")
install.packages("ggmap")
install.packages("tidyr")
install.packages("stringr")
install.packages("dplyr")
install.packages("janeaustenr")
install.packages("tidytext")
install.packages("reshape2")
install.packages("SnowballC")
install.packages("NLP")
install.packages("tmap")
install.packages("tmaptools")
install.packages("maps")
install.packages("maptools")
install.packages("dplyr")
install.packages("tidyr")
install.packages("rgdal") 
install.packages("rgeos")
install.packages("sp")
install.packages("tidytext")
install.packages("topicmodels")
install.packages("tidyr")
install.packages("stringr")
install.packages("janeaustenr")
install.packages("reshape2")
install.packages("tidyverse")
install.packages("tibble")
install.packages("tidyr")
install.packages("purrr")
install.packages("readr")
install.packages("vegan") 
install.packages("vegdata")
install.packages("mclust")
install.packages("cluster")
install.packages("gains")
install.packages("animation")
install.packages("BSDA")
install.packages("broom")
install.packages("caret")
install.packages("car")
install.packages("carData")
install.packages("caretEnsemble")
install.packages("cluster.datasets")
install.packages("ClusterR")
install.packages("e1071")
install.packages("enembleR")
install.packages("gams")
install.packages("geosphere")
install.packages("ggRandomForests")
install.packages("ipred")
install.packages("kernlab")
install.packages("leaflet")
install.packages("NbClust")
install.packages("randForest")
install.packages("raster")
install.packages("rattle")

Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jre8') # C:\Program Files\Java\jre1.8.0_181 for 64-bit version
Sys.setenv(JAVA_HOME='C:\\Program Files (x86)\\Java\\jre8') # for 32-bit version
library(rJava)

if (Sys.getenv("JAVA_HOME")!="")
	Sys.setenv(JAVA_HOME="")
.jinit()
.jcall('java.lang.System','S','getProperty','java.version')
install.packages("~/R/win-library/3.5/ReporteRsjars_0.0.4.tar.gz", repos = NULL, type = "source")
install.packages("~/R/win-library/3.5/ReporteRs_0.8.10.tar", repos = NULL, type = "source")
